### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by FansubDB** [FansubDB/fansubdb.github.io#103]
- Link to Swagger and explain API with that
---
 - [ ] rename `message` to `message_empty_list` for the AnimeoftheSeason struct
 - [ ] rename `name` to `name_lbl` for the AnimeoftheSeason struct
 - [ ] rename `group` to `group_lbl` for the AnimeoftheSeason struct
 - [ ] rename `lbl_[...]` to `[...]_lbl` for the AnimeoftheSeason struct
 - [ ] rename `group` to `groups` for the Anime struct
---
 - [ ] remove `title` for Languages struct (use `lang` + capitalize)
 - [ ] remove `index` for Languages struct (use `url` + index.html)
 - [ ] rename `view-page` to `goto_lbl` for Languages struct
---
 - [ ] rename `msg` to `datafrom_msg` for Languages struct
 - [ ] remove `msg_season` for Languages struct (use `erroryearorseason_msg`)
 - [ ] remove `msg_year` for Languages struct (use `erroryearorseason_msg`)
 - [ ] rename `msg_all` to `erroryearorseason_msg` for Languages struct
